### ISSUE TITLE
MTRNord's TODO/Wishlist

### ISSUE THREAD

**Issue by MTRNord** [the-draupnir-project/Draupnir#151]
(This is an informal list of things I want to work on, or I am working on. Hence, a grouped Issue. Feel free to extract tasks and work on them, though. Tick means work is happening already.)

- [x] Yara Rules (#139)
- [x] MSC1929 (#150)
- [ ] Updating the rest of the commands to the new system
- [ ] Updating the synapse module
- [x] bot-sdk crypto (#145)
- [ ] Adding the policy list system to protections
- [ ] Extending the documentation especially for protections
- [ ] Improving tests
- [ ] Improving code quality where sensible
