### ISSUE TITLE
[D4ALL] Tracking issue for upstreaming

### ISSUE THREAD

**Issue by MTRNord** [the-draupnir-project/Draupnir#264]
Just some code chunks that are ready to upstream but are not yet:

- [ ] https://github.com/the-draupnir-project/Draupnir/compare/main...MTRNord/draupnir4all#diff-fc1ae6fc57c3f4d2354cfe93e7a5f071f66346bb04c9e5ce0e7ea11edaa9db07R115-R130
- [ ] https://github.com/the-draupnir-project/Draupnir/compare/main...MTRNord/draupnir4all#diff-086b2630c107800e8986aece43aa5fd570d859b3f8ac40577df049f73c6a6291R172
- [ ] https://github.com/the-draupnir-project/Draupnir/compare/main...MTRNord/draupnir4all#diff-fc1ae6fc57c3f4d2354cfe93e7a5f071f66346bb04c9e5ce0e7ea11edaa9db07R176-R190
- [ ] https://github.com/the-draupnir-project/Draupnir/compare/main...MTRNord/draupnir4all#diff-b7e2bd277eaf565e97929be4143f60bd7274e4ed9b38c913ed2f46ace5a5b620R237-R275
- [ ] https://github.com/the-draupnir-project/Draupnir/compare/main...MTRNord/draupnir4all#diff-472f8bfb63217e1195d0f94d97cf8795046dd77ad684e22bcd72fa92a5890475R53-R99

**Comment by MTRNord** [comment]
There is also the whole tracing stuff but I am not super happy with the code for it right now so I dont think it can be upstreamed yet
